### ISSUE TITLE
Can't use v2 using `go get`

### ISSUE THREAD

**Issue by mca312** [talon-one/talon_go#11]
`go get github.com/talon-one/talon_go` installs v1.4 and `go get github.com/talon-one/talon_go/v2` doesn't exist.  Can you add `/v2` to `go.mod`?

**Comment by altJake** [comment]
Hi @mca312 ,

Thank you for noticing the issue and bring it to our attention.

We have fixed the issue and made a minor version release:
 - You can see the new release page here at the repository: [v2.3.1](https://github.com/talon-one/talon_go/releases/tag/v2.3.1)
 - And also now you can see the correct release at the [pkg.go.dev](https://pkg.go.dev/github.com/talon-one/talon_go/v2) proxy
 
I will close the issue for now, if you see any further issues with acquiring our package, please comment here and we will make sure to take care of it.

Thanks a lot again
