### ISSUE TITLE
`GetCustomerSession` and `ReturnCartItems` methods missing

### ISSUE THREAD

**Issue by karthikraobr** [talon-one/talon_go#18]
As the title says the methods `GetCustomerSession` and `ReturnCartItems`  are missing on the type `IntegrationApiService`. Could you please look into this. Thanks!

**Comment by altJake** [comment]
Hey @karthikraobr, @jwra, @ogallardop,

@karthikraobr, thank you very much for reporting the issue, unfortunately we have been neglecting the Go SDK for quite long, and haven't pushed the latest feature here. It's great to see that there's demand and that the SDK is being used.

Please check out the latest release ([v2.6.0](https://github.com/talon-one/talon_go/releases/tag/v2.6.0)) from today, which should include the missing functionalities you have mentioned.

Thanks again for your contribution, and in case you have any follow up questions, please don't hesitate to drop us a message here!
